//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagmentSystem_
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift
    {
        public int id_shift { get; set; }
        public Nullable<int> id_worker { get; set; }
        public string specialization_shift { get; set; }
        public Nullable<System.DateTime> date_shift { get; set; }
    
        public virtual worker worker { get; set; }
    }
}
